name: Maven Build

on:
  push:

jobs:
  build:
    permissions:
      checks: write
      contents: read
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

#      - name: emit colima version
#        run: colima --version
#
#      - name: add docker version
#        run: |
#          brew install docker docker-Buildx
#
#      - name: emit docker version
#        run: |
#          docker --version
#
##      - name: link docker
##        run: |
##          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
##          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - name: Build and Run Tests
        run: mvn test --batch-mode --fail-at-end
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1.7.2
